services:
  db:
    image: postgres:15-alpine
    container_name: lecsens-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: user_service
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d user_service"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - lecsens-network
    restart: unless-stopped
  app:
    build: .
    container_name: lecsens-app
    image: be-lecsens-user_management
    ports:
      - "3120:3120"
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: root
      DB_PASSWORD: P@ssw0rd
      DB_NAME: user_service
      PORT: 3120
      GIN_MODE: release
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lecsens-network
    restart: unless-stopped

networks:
  lecsens-network:
    name: be-lecsens_network
    driver: bridge

volumes:
  pgdata:
    name: be-lecsens_pgdata